### ISSUE TITLE
Error: No tasks were provided to run-sequence

### ISSUE THREAD

**Issue by davestewart** [EHLOVader/laravel-elixir-livereload#20]
Using the example code as such:

```
elixir(function(mix) {
    mix.livereload();
});
```

I get:

```
[14:08:24] Using gulpfile /Volumes/Data/Work/OpenSource/PHP/Laravel/Laravel Sketchpad/sketchpad-demo/support/gulpfile.js
[14:08:24] Starting 'default'...
[14:08:24] 'default' errored after 547 μs
[14:08:24] Error: No tasks were provided to run-sequence
    at verifyTaskSets (/Volumes/Data/Work/OpenSource/PHP/Laravel/Laravel Sketchpad/sketchpad-demo/support/node_modules/laravel-elixir/node_modules/run-sequence/index.js:10:9)
    at runSequence (/Volumes/Data/Work/OpenSource/PHP/Laravel/Laravel Sketchpad/sketchpad-demo/support/node_modules/laravel-elixir/node_modules/run-sequence/index.js:94:2)
    at Gulp.<anonymous> (/Volumes/Data/Work/OpenSource/PHP/Laravel/Laravel Sketchpad/sketchpad-demo/support/node_modules/laravel-elixir/tasks/default.js:18:16)
    at module.exports (/Volumes/Data/Work/OpenSource/PHP/Laravel/Laravel Sketchpad/sketchpad-demo/support/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Volumes/Data/Work/OpenSource/PHP/Laravel/Laravel Sketchpad/sketchpad-demo/support/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Volumes/Data/Work/OpenSource/PHP/Laravel/Laravel Sketchpad/sketchpad-demo/support/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Volumes/Data/Work/OpenSource/PHP/Laravel/Laravel Sketchpad/sketchpad-demo/support/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

```

It's the only elixir task I have.

If I do add another task, it runs, but doesn't appear to watch and wait in the terminal, like a normal gulp.watch() would, so I suspect that somehow the task is not being added to elixir?

I know it's loading as I stuck a gulp-util.log in your index file, and it ran.

I don't use elixir regularly, but I'm trying it out now to add as an alternative to the standard watch (by the way, I got all that sorted in the end; no plugin needed, just gulp-watch and a monkey patch clientside)

**Comment by wacxg** [comment]
I have the same problem.

    "gulp": "^3.9.1",
    "laravel-elixir": "^5.0.0",
    "laravel-elixir-livereload": "^1.1.6"

when i use 'gulp' command , it will report the same errors.
   No tasks were provided to run-sequence
